xquery version "1.0-ml";

module namespace ar = "http://lds.org/code/shared/lds-edit/render-functions";

import module namespace video = "http://lds.org/code/shared/common/video/video-functions" at "/shared/common/video/videoFunctions.xqy";

import module namespace util = "http://lds.org/code/shared/lds-edit/ldse-util-functions" at "utility-functions.xqy";
import module namespace ldsemeta = "http://lds.org/code/shared/lds-edit/meta-functions" at "ldse-meta.xqy";
import module namespace form = "http://lds.org/code/shared/lds-edit/dynamicForms" at "../ice/modules/dynamicForms.xqy";
import module namespace ice = "http://lds.org/code/shared/lds-edit/iceFunction" at "../ice/modules/iceFunctions.xqy";
import module namespace c = "http://lds.org/code/shared/common/common-functions" at "/shared/common/commonFunctions.xqy";

import module namespace settings = "http://lds.org/code/shared/lds-edit/ldse-settings" at "ldse-settings.xqy";
import module namespace core = "http://lds.org/code/shared/lds-edit/ldse-core" at "ldse-core.xqy";
import module namespace enrich = "http://lds.org/code/shared/lds-edit/enrich" at "../enrich/enrich-functions.xqy";

(: Site custom module :)
import module namespace srf = "http://lds.org/code/shared/lds-edit/custom/render-functions" at "/custom/lds-edit/render-functions.xqy";

declare namespace ldse = "http://lds.org/code/lds-edit";
declare namespace xhtml = "http://www.w3.org/1999/xhtml";
declare option xdmp:mapping "true";

(: Used to process the xml generated by the lds-edit ckeditor :)
declare function getDefaultOptions() as element(options) {
    <options>
        <host>{ $util:host }</host>
        <protocol>{ $util:protocol }</protocol>
        <video-service-url>{ util:get-service-url('videoService') }</video-service-url>
        <config-files>{
            $settings:ldse-settings,
            ice:getCkeditorSettings()
        }</config-files>
        <brightcove-width>480</brightcove-width>
        <brightcove-height>270</brightcove-height>
        <brightcove-autostart>false</brightcove-autostart>
        <brightcove-location></brightcove-location>
        <brightcove-gallery-width>480</brightcove-gallery-width>
        <brightcove-gallery-height>460</brightcove-gallery-height>
        <image-caption-class>img-caption</image-caption-class>
        <image-align-right-class>img-right</image-align-right-class>
        <image-align-left-class>img-left</image-align-left-class>
        <image-align-full-class>img-full-width</image-align-full-class>
    </options>
};

(: Sites can call this one :)
declare function processWysiwygText(
    $wysiwygText as item()*,
    $deprecated-context as xs:string?,
    $locale as xs:string,
    $url as xs:string
) as item()* {
    processAndEnrich($wysiwygText, $locale, $url, getDefaultOptions(), fn:root($wysiwygText[1])//ldse:enrich[1])
};

(: Sites can call this one :)
declare function processWysiwygText(
    $wysiwygText as item()*,
    $deprecated-context as xs:string?,
    $locale as xs:string,
    $url as xs:string,
    $options as element()?
) as item()* {
    processAndEnrich($wysiwygText, $locale, $url, util:merge(getDefaultOptions(), $options), fn:root($wysiwygText[1])//ldse:enrich[1])
};

(: Sites can call this one :)
declare function processWysiwygText(
    $wysiwygText as item()*,
    $deprecated-context as xs:string?,
    $locale as xs:string,
    $url as xs:string,
    $options as element()?,
    $enrich as element(ldse:enrich)?
) as item()* {
   processAndEnrich($wysiwygText, $locale, $url, util:merge(getDefaultOptions(), $options), $enrich)
};

(: Called if the options has already been merged :)
declare function processAndEnrich(
    $wysiwygText as item()*,
    $locale as xs:string,
    $url as xs:string,
    $options as element()?,
    $enrich as element(ldse:enrich)?
) as item()* {
    let $proccessed-text as item()* := process($wysiwygText, $locale, $url, $options)
    return (
        if ( fn:exists($enrich) ) then (
            enrich:mark-up-text(<text>{$proccessed-text}</text>, $enrich, util:get-lang-from-locale($locale))/node()
        ) else (
            $proccessed-text
        )
    )
};

(: Called if the options has already been merged :)
declare function process(
    $wysiwygText as item()*,
    $locale as xs:string,
    $url as xs:string,
    $options as element()?
) as item()* {
    for $node as item() in $wysiwygText
    return (
        typeswitch ($node)
        case text() return srf:processText($node, $locale, $url, $options)
        case element() return (
            typeswitch ( element {fn:local-name($node)} {} )
            case element(p)  return srf:processPara($node, $locale, $url, $options)
            case element(a) return srf:processLink($node, $locale, $url, $options)
            case element(img) return srf:processImg($node, $locale, $url, $options)
            case element(pre) return srf:processPre($node, $locale, $url, $options)
            case element(block) return srf:processBlock($node, $locale, $url, $options)
            case element(iframe) return processIframe($node, $locale, $url, $options)
            default return srf:defaultProcess($node, $locale, $url, $options)
        )
        case comment() return srf:processComment($node, $locale, $url, $options)
        case document-node() return process($node/node(), $locale, $url, $options)
        default return ()
    )
};

declare function processComment(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    ()
};

declare function processText(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    $node
};

declare function processLink(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $host as xs:string := $options/host
    let $lang as xs:string := util:get-lang-from-locale($locale)
    let $isScriptureReference as xs:boolean := fn:starts-with($node/@href, '/scriptures/')
    let $isOldScriptureReference as xs:boolean := (fn:contains($node/@href, 'scriptures.lds.org') or fn:contains($node/@href, 'scriptures.churchofjesuschrist.org'))
    let $isMailTo as xs:boolean := fn:starts-with(fn:lower-case($node/@href), 'mailto:')
    let $isLinkToAnchor as xs:boolean := fn:starts-with($node/@href, '#')
    let $isAnchor as xs:boolean := ( fn:empty($node/@href) and $node/@name ne '' )
    let $onclick as attribute()? := if ($node/@popup eq "true") then ( attribute onclick {'newWindow(this.href); return false;'} ) else ($node/@onclick)
    let $innerText as item()* := process($node/node(), $locale, $url, $options)
    let $attributes as attribute()* := (
        $node/@*[fn:not(fn:node-name(.) eq (xs:QName('href'), xs:QName('onclick'), xs:QName('popup') ) )]
    )
    let $suppresslangparam as xs:string? := $options/suppresslangparam
    let $devopprefix as xs:string? := $options/devopprefix
    let $lang-hosts as xs:string* := $settings:lang-hosts
    let $need-lang as xs:boolean? :=
            (for $lang-host as xs:string in $lang-hosts
            where fn:contains($node/@href, $lang-host) or fn:contains($host, $lang-host)
            return fn:true())[1]
    let $href as xs:string? :=
        if ( fn:contains($node/@href, 'mailto:') ) then (
            'mailto:' || fn:substring-after($node/@href, 'mailto:')
        ) else if ( fn:starts-with($node/@href, '#') ) then (
            $node/@href
        ) else if ( fn:starts-with($node/@href, "http://") or fn:starts-with($node/@href, "https://") or fn:starts-with($node/@href, '//') or $need-lang ) then (
            let $map := map:map()
            let $put := map:put($map, 'host', $host)
            let $put := map:put($map, 'lang', $locale)
            let $put := map:put($map, 'suppresslangparam', $suppresslangparam)
            let $hash as xs:string? := fn:tokenize($node/@href, '#')[2]
            let $url as xs:string? :=
                if ( fn:exists($hash) ) then (
                    fn:tokenize($node/@href, '#')[1]
                ) else ( $node/@href )
            let $url as xs:string? :=
                if ( fn:starts-with($url, '/') and fn:not(fn:starts-with($url, '//')) and string-length($devopprefix) > 0) then
                    $devopprefix || $url
                else
                    $url
            let $new-url as xs:string? := util:get-url-with-lang($url, $map)
            return (
                if ( fn:exists($hash) ) then (
                    $new-url || '#' || $hash
                ) else ( $new-url )
            )
        ) else if ( $node/@href = '' ) then (
            $node/@href
        ) else ( util:build-full-url($host, $node/@href, $lang) )

    return (
        if ($isScriptureReference) then (
            let $language as element(language)? := util:get-language-by-locale($lang)
            let $verses as xs:string* :=
                if (fn:tokenize($node/@href, '\.')[2] != "") then (
                    fn:tokenize(fn:tokenize($node/@href, '\.')[2], '\?')[1]
                ) else if (fn:tokenize($node/@href, '#')[2] != "") then (
                    fn:tokenize($node/@href, '#')[2]
                ) else ()
            let $href as xs:string := fn:tokenize($node/@href, '#')[1]
            let $hash as xs:string? := fn:tokenize($node/@href, '#')[2]
            let $hash as xs:string? := if ( fn:exists($hash) ) then ( '#' || $hash ) else ()
            let $href as xs:string :=
                if ( fn:starts-with($href, "http://") or fn:starts-with($href, "https://") or fn:starts-with($href, '//') or $need-lang ) then (
                    let $map := map:map()
                    let $put := map:put($map, 'host', $host)
                    let $put := map:put($map, 'lang', $locale)
                    let $url as xs:string :=
                        if ( fn:starts-with($href, '/') and fn:not(fn:starts-with($href, '//')) ) then (
                            $host || $href
                        ) else ( $href )
                    return util:get-url-with-lang($url, $map) || $hash
                ) else (
                    util:build-full-url($host, $href, $lang)
                )
            (: If the URL contains any of the testament segments then we found a match :)
            let $hasTestament := $language/../content-links/testaments/contains[fn:contains($href, @segment)]/@node/fn:string()
            let $renderLink as xs:boolean :=
                (
                  (: If the URL doesn't contain any of the testament segments then it is not scripture. :)
                  fn:not($hasTestament) or
                  (: Verify that the language supports the given testament. :)
                  ($language/*[fn:local-name(.) = $hasTestament] eq 'true')
                )
            return (
                if ($renderLink) then (
                    element a {
                        attribute href {
                            if (fn:not(fn:contains($href, 'lang='))) then (
                                fn:concat(
                                    util:build-full-url($host, $href, $lang),
                                    if (fn:exists($verses)) then (
                                        let $anchor as xs:string? := fn:tokenize($verses,'-')[1]
                                        let $anchor as xs:string? := if ($anchor castable as xs:integer) then ($anchor) else (fn:tokenize($verses, ',')[1])
                                        let $anchor as xs:string? := if($anchor castable as xs:integer) then ( xs:string(xs:integer($anchor) - 1) ) else ()
                                        return if (fn:exists($anchor)) then (fn:concat('#', $anchor)) else ()
                                    ) else ()
                                )
                            ) else (
                                fn:concat(
                                    $href,
                                    if ( fn:exists($verses) ) then (
                                        let $anchor as xs:string? := fn:tokenize($verses,'-')[1]
                                        let $anchor as xs:string? := if($anchor castable as xs:integer) then ( xs:string( xs:integer($anchor) - 1 ) ) else ()
                                        return if (fn:exists($anchor)) then (fn:concat('#', $anchor)) else ()
                                    ) else ()
                                )
                            )
                        },
                        attribute onclick {'newWindow(this.href); return false;'},
                        $attributes,
                        $innerText
                    }
                ) else (
                    $innerText
                )
            )
        ) else if ($isLinkToAnchor) then (
            element a {
                attribute href { $href },
                $attributes,
                $onclick,
                $innerText
            }
        ) else if ($isAnchor) then (
             element a{
                $attributes,
                $innerText
            }
        ) else if ($isMailTo) then (
           element a{
                attribute href { $href },
                $attributes,
                $innerText
            }
        ) else if ($isOldScriptureReference) then (
           element a{
                attribute href { $href },
                $attributes,
                attribute onclick {'newWindow(this.href); return false;'},
                $innerText
            }
        ) else (
            element a {
                attribute href { $href },
                $attributes,
                $onclick,
                $innerText
            }
        )
    )
};


declare function processImg(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $url := c:getHost() || '/' ||fn:substring-after(fn:substring-after($url, '//'), '/')
    let $caption as xs:string? := $node/@caption
    let $imgAlign as xs:string? := fn:string($node/@align)
    let $protected as xs:string? := $node/@protected
    let $wrapperClass as xs:string? :=
        fn:concat(
            if ($caption ne '') then ( fn:concat($options/image-caption-class, " ") ) else (),
            if ($imgAlign eq "right") then ($options/image-align-right-class)
            else if ($imgAlign eq "left") then ($options/image-align-left-class)
            else if ($imgAlign eq "full") then ($options/image-align-full-class)
            else ()
        )
    let $img as element(img) :=
        element img {
            $node/@*[fn:not( fn:node-name(.) eq (xs:QName('protected'), xs:QName('caption'), xs:QName('align')) )]
        }
    let $image as element() :=
        if ( fn:exists($protected) ) then (
            <div class="img-overlay">
                <div class="img-trans">&nbsp;</div>
                {$img}
            </div>
        ) else ( $img )
    return (
        if ($wrapperClass ne '') then (
            <div class="{$wrapperClass}">{
                $image,
                if ( $caption ne '' ) then (
                  <p>{ form:stripJavascript(ice:tidy($caption)) }</p>
                ) else ()
            }</div>
        ) else ($image)
    )
};

declare function processPre(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $typeId as xs:string* := fn:tokenize(fn:substring-before(fn:substring-after($node,"["),"]"),":")
    let $type as xs:string? := $typeId[1]
    let $id as xs:string? := $typeId[2]
    where $type ne '' and $id ne ''
    return (
        if ($type eq 'teaser') then (
            srf:buildTeaser($id, $locale, $url, $options)
        ) else if ($type eq 'brightcove') then (
            srf:buildInlineBrightCove($id, $locale, $url, $options)
        ) else if ($type eq 'gallery') then (
           srf:buildInlineBrightCoveGallery($id, $locale, $url, $options)
        ) else (
            srf:defaultInlineObject($type, $id, $locale, $url, $options)
        )
    )
};

declare function buildTeaser(
    $id as xs:string,
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $teaser as element(teaser)? :=
        cts:search(/teaser,
            cts:and-query((
                core:get-filter-query(),
                cts:element-attribute-value-query(xs:QName('teaser'), xs:QName('id'), $id, 'exact')
            ))
        )[1]
    where fn:exists($teaser)
    return (
        let $title as xs:string? := fn:normalize-space($teaser/title)
        let $titleUrl as xs:string? := $teaser/url
        let $teaserLocale as xs:string? := fn:data($teaser/@locale)
        let $titleWithLink as element()* :=
            if ($title ne '') then (
                <h2>{
                    if ($titleUrl ne '') then (
                        <a href="{$titleUrl}">{$title}</a>
                    ) else ($title)
                }</h2>,
                <hr/>
              ) else ()
        let $text as item()* := if ( fn:exists($teaser/text/*) ) then ($teaser/text/node()) else (ice:tidy($teaser/text))
        let $links as element()* := $teaser/links
        let $class as xs:string := fn:concat('box-decor box-',$teaser/align)
        let $formName as xs:string? := getPluginForm("inlineteaser", $options)
        let $ice as item()* := ice:add-ice($teaserLocale, 'teaser', $teaser, $url,
                                     <options>
                                        <variables>
                                            <form>{$formName}</form>
                                        </variables>
                                        <settings>
                                            <only-one>true</only-one>
                                        </settings>
                                     </options>)
        return (
            <div class="{$class}">
                { $ice }
                { $titleWithLink }
                { process($text, $locale, $url, $options) }
                {
                    if (there-are-links($links)) then (
                        element ul {
                            attribute class { "list-decor" },
                            add-list-item-links($links)
                        }
                    ) else ()
                }
            </div>
        )
    )
};

declare function there-are-links(
    $links as element(links)*
) as xs:boolean {
    fn:not(fn:normalize-space($links/title/fn:string()) = '')
};

declare function add-list-item-links(
    $links as element(links)*
) as element(li)* {
    (: add link li elements :)
    for $link as element(link) in $links/link
    let $linkTitle as xs:string? := $link/title
    let $linkUrl as xs:string? := $link/url
    where $linkTitle ne ''
    return (
        element li {
            if ($linkUrl ne '') then (
                element a { attribute href { $linkUrl }, $linkTitle }
            ) else ( $linkTitle )
        }
    )
};

declare function brightcoveMediaLoaderScript(
    $id as xs:string,
    $videoId as xs:string?,
    $playerId as xs:string?,
    $playerKey as xs:string?,
    $linkUrl as xs:string?,
    $width as xs:string?,
    $height as xs:string?,
    $protocol as xs:string?,
    $autoLoad as xs:string?,
    $autoStart as xs:string?
) as element(script)? {
    <script type='text/javascript'>
        LDS.mediaList["{$id}"] = {{
            "type":"bc",
            {if ($autoLoad) then fn:concat( '"autoLoad":"', if ($autoLoad = ('true','false')) then $autoLoad else 'false', '",' ) else ()}
            "params": {{
                {fn:concat( '"autoStart":', if ($autoStart = ('true','false')) then $autoStart else 'false', ',')}
                {if ($linkUrl) then fn:concat( '"linkBaseURL":"', $linkUrl, '",' ) else ()}
                "@videoPlayer":"{$videoId}",
                "playerID":'{$playerId}',
                "playerKey":'{$playerKey}',
                {if ($width) then fn:concat( '"width":', $width, ',') else ()}
                {if ($height) then fn:concat( '"height":', $height, ',') else ()}
                "secureConnections":{$protocol eq "https"}
            }}
        }};
        LDS.ComponentCallbacks["media-loader"] = function(){{
            yepnope({{
                load: [
                    "{fn:concat( $settings:cdn-path, $settings:medialoader-path )}"
                ],
                complete:function(){{
                    $(".js-media-loader").mediaLoader({{ useHash: false, leaveOthersOpen: true}});
                }}
            }});
        }};
    </script>
};

declare function buildInlineBrightCove(
    $id as xs:string,
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $host as xs:string := $options/host
    let $protocol as xs:string := $options/protocol
    let $width as xs:string? := $options/brightcove-width
    let $height as xs:string? := $options/brightcove-height
    let $location as xs:string? := $options/brightcove-location
    let $autostart as xs:string := ( $options/brightcove-autostart/fn:string(), 'false' )[1]
    let $video as element()? := getBrightcoveVideoById($id, $locale)
    let $translatedVideo as item()* := video:translateVideo($video, util:get-lang-from-locale($locale))
    let $playerId as xs:string? := $video/no-search/player-id/fn:string()
    let $videoId as xs:string? :=  if ( $options/video-service-url ne '' ) then ( fn:normalize-space($translatedVideo/id) ) else ( fn:normalize-space($video/no-search/video-id) )
    let $playerKey as xs:string? := $video/no-search/player-key/fn:string()
    let $sharedUrl as xs:string := util:build-full-url($host, $url, $locale)

    let $formName as xs:string? := getPluginForm("brightcove", $options)
    let $ice as item()* :=
        if ($formName ne '') then (
            ice:add-ice($locale, 'video', $video, $url,
                        <options>
                            <variables>
                                <form>{$formName}</form>
                                <location>{$location}</location>
                            </variables>
                            <settings>
                                <only-one>true</only-one>
                            </settings>
                        </options>)
        ) else ()
    where fn:exists($video) and $videoId ne ''
    return (
        <div class="brightCoveWrapper">{$ice}
            <!-- /lds-edit/modules/render-functions/inline -->
            <div class="js-media-loader" id="{$id}">&nbsp;</div>
            {
                srf:brightcoveMediaLoaderScript($id, $videoId, $playerId, $playerKey, $sharedUrl, $width, $height, $protocol, 'true', $autostart )
            }
        </div>
    )
};

declare function buildInlineBrightCoveGallery(
    $id as xs:string,
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    let $host as xs:string := $options/host
    let $protocol as xs:string := $options/protocol
    let $width as xs:string? := $options/brightcove-gallery-width
    let $height as xs:string? := $options/brightcove-gallery-height
    let $video as element()? := getBrightcoveGalleryById($id, $locale)
    let $playerId as xs:string? := $video/no-search/player-id
    let $videoId as xs:string? := fn:normalize-space($video/no-search/video-id)
    let $playerKey as xs:string? := $video/no-search/player-key
    let $sharedUrl as xs:string := util:build-full-url($host, $url, $locale)

    let $formName as xs:string? := getPluginForm("gallery", $options)
    let $ice as item()* := if ($formName ne '') then (
                    ice:add-ice($locale, 'video', $video, $url,
                                            <options>
                                                <variables>
                                                    <video-player>gallery</video-player>
                                                    <form>{$formName}</form>
                                                </variables>
                                                <settings>
                                                    <only-one>true</only-one>
                                                </settings>
                                            </options>)
                ) else ()
    where fn:exists($video)
    return (
        <div class="brightCoveWrapper">{$ice}
            <!-- /lds-edit/modules/render-functions/gallery -->
            <div id="{$id}">&nbsp;</div>
            {
                srf:brightcoveMediaLoaderScript($id, $videoId, $playerId, $playerKey, $sharedUrl, $width, $height, $protocol, 'true', 'false' )
            }
        </div>
    )
};


declare function processPara(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    if ( some $text in $node//text() satisfies $text != '' ) then (
        element p {
            $node/@*,
            process($node/node(), $locale, $url, $options)
        }
    ) else (
        process($node/node(), $locale, $url, $options)
    )
};

declare function processBlock(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    element {if ($node/@type eq 'div') then ('div') else ('p') } {
        $node/@*[fn:not(fn:node-name(.) = xs:QName("type"))],
        process($node/node(), $locale, $url, $options)
    }
};

declare function processIframe(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    element { fn:local-name($node) } {
        $node/@*[fn:not(fn:node-name(.) = xs:QName("type"))],
        " "
    }
};

declare function defaultProcess(
    $node as item(),
    $locale as xs:string,
    $url as xs:string,
    $options as element(options)
) as item()* {
    element { fn:local-name($node) } {
        $node/@*,
        process($node/node(), $locale, $url, $options)
    }
};

declare function getBrightcoveVideoById(
    $id as xs:string,
    $locale as xs:string
) as element()? {
    cts:search(/ldswebml,
        cts:and-query((
           core:get-filter-query(),
           cts:element-value-query(xs:QName('source'), $id, 'exact'),
           cts:element-attribute-value-query(xs:QName('ldswebml'), xs:QName('type'), 'video', 'exact'),
           cts:element-attribute-value-query(xs:QName('ldswebml'), xs:QName('locale'), $locale, 'exact'),
           cts:not-query(cts:element-value-query(xs:QName('video-id'), '', 'exact'))

        ))
    )[1]
};

declare function getBrightcoveGalleryById(
    $id as xs:string,
    $locale as xs:string
) as element()? {
    cts:search(/ldswebml,
        cts:and-query((
           core:get-filter-query(),
           cts:element-value-query(xs:QName('source'), $id, 'exact'),
           cts:element-value-query(xs:QName('player'), 'gallery', 'exact'),
           cts:element-attribute-value-query(xs:QName('ldswebml'), xs:QName('type'), 'video', 'exact'),
           cts:element-attribute-value-query(xs:QName('ldswebml'), xs:QName('locale'), $locale, 'exact')

        ))
    )[1]
};

declare function getPluginForm(
    $plugin as xs:string,
    $options as element(options)
) as xs:string? {
    ($options/config-files/ldse:ldse-ckeditor/ldse:plugins/ldse:plugin[. eq $plugin]/@form/xs:string(.))[1]
};
