xquery version "1.0-ml";
module namespace moc = "http://lds.org/code/shared/lds-edit/mormonOrgComponents";
declare function moc:get-mormon-org-components(
)
{
        (
				<mo-action-bar>Action Bar</mo-action-bar>,
				<mo-anchor>Anchor</mo-anchor>,
				<mo-audio-player>Audio Player</mo-audio-player>,
				<mo-block-quote>Block Quote</mo-block-quote>,
				<mo-button>Button</mo-button>,
				<mo-card-tile>Card Tile</mo-card-tile>,
				<mo-chat>Chat</mo-chat>,
				<mo-church-product>Church Product</mo-church-product>,
				<mo-content-block>Content Block</mo-content-block>,
				<mo-cookie-based-display>Cookie Based Display</mo-cookie-based-display>,
				<mo-counter>Counter</mo-counter>,
				<mo-digit>Digit</mo-digit>,
				<mo-drawer>Drawer</mo-drawer>,
				<mo-drawers>Drawers</mo-drawers>,
				<mo-dynamic-i18n-selector>Dynamic I18n Selector</mo-dynamic-i18n-selector>,
				<mo-emphasized-media-tile>Emphasized Media Tile</mo-emphasized-media-tile>,
				<mo-emphasized-video>Emphasized Video</mo-emphasized-video>,
				<mo-enhanced-ui-slider>Enhanced Ui Slider</mo-enhanced-ui-slider>,
				<mo-flip-card>Flip Card</mo-flip-card>,
				<mo-floating-action-button>FAB</mo-floating-action-button>,
				<mo-footer>Footer</mo-footer>,
				<mo-heading>Heading</mo-heading>,
				<mo-horizontal-rule>Horizontal Rule</mo-horizontal-rule>,
				<mo-horizontal-tile>Horizontal Tile</mo-horizontal-tile>,
				<mo-iframe>Iframe</mo-iframe>,
				<mo-inline-component-gallery>Inline Component Gallery</mo-inline-component-gallery>,
				<mo-jumbo-cta>Jumbo CTA</mo-jumbo-cta>,
				<mo-link-list>Link List</mo-link-list>,
				<mo-media-block>Media Block</mo-media-block>,
				<mo-meetinghouse-cta>Meetinghouse CTA</mo-meetinghouse-cta>,
				<mo-mini-cta>Mini CTA</mo-mini-cta>,
				<mo-mini-lesson>Mini Lesson</mo-mini-lesson>,
				<mo-modal>Modal</mo-modal>,
				<mo-multi-buttons>Multi Buttons</mo-multi-buttons>,
				<mo-page-header-nav>Page Header Nav</mo-page-header-nav>,
				<mo-pagination>Pagination</mo-pagination>,
				<mo-param-relay>Param Relay</mo-param-relay>,
				<mo-persistent-cta>CTA Persistent</mo-persistent-cta>,
				<mo-personalized-content>Personalized Content</mo-personalized-content>,
				<mo-poll>Poll</mo-poll>,
				<mo-prebuilt-form>Prebuilt Form</mo-prebuilt-form>,
				<mo-pull-quote>Pull Quote</mo-pull-quote>,
				<mo-related-articles>Related Articles</mo-related-articles>,
				<mo-search-form>Search Form</mo-search-form>,
				<mo-search-results>Search Results</mo-search-results>,
				<mo-series-wayfinder>Series Wayfinder</mo-series-wayfinder>,
				<mo-simple-sign-up>Simple Sign Up</mo-simple-sign-up>,
				<mo-social-block>Social Block</mo-social-block>,
				<mo-spacing>Spacing</mo-spacing>,
				<mo-spot-illustration>Spot Illustration</mo-spot-illustration>,
				<mo-spot-link-block>Spot Link Block</mo-spot-link-block>,
				<mo-stepped-form>Stepped Form</mo-stepped-form>,
				<mo-swap-component>Swap Component</mo-swap-component>,
				<mo-tag-list>Tag List</mo-tag-list>,
				<mo-text-link-list>Text Link List</mo-text-link-list>,
				<mo-tile-swipe>Tile Swipe</mo-tile-swipe>,
				<mo-topic-card>Topic Card</mo-topic-card>,
				<mo-uber-tile>Uber Tile</mo-uber-tile>
	)
};
